DROP DATABASE IF EXISTS PARKP2P;
CREATE DATABASE PARKP2P;
USE PARKP2P;
CREATE TABLE driveways
(

	ID INT AUTO_INCREMENT NOT NULL,
    Email VARCHAR(80) UNIQUE NOT NULL,
    Pass BINARY(60) NOT NULL,
	PRIMARY KEY(ID)
);

	USE PARKP2P;
	INSERT INTO driveways (Email, Pass)
	values ("test@gmail.com", "hashedpassword")